### ISSUE TITLE
Can't download Episode

### ISSUE THREAD

**Issue by Zeniitsu** [anidl/crunchyroll-downloader-nx#23]
Everything was working normally
Today this problem appeared

@ C:\Users\Administrator\Downloads\crunchyroll-downloader-nx-4.19.1-win64\crunch
yroll-downloader-nx-4.19.1-win64

> crunchy.exe node crunchy -s 25192 -e 11

=== Crunchyroll Downloader NX 4.19.1 ===

[INFO] Cookies were updated! (etp_rt)

[S:25192] Rent-a-Girlfriend [simulcast]
  [0001|796247] 1 - Rent-a-Girlfriend
   - PremPubDate: 2020-07-10 18:30:00 UTC
   - FreePubDate: 2020-07-17 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0002|796248] 2 - Ex-Girlfriend and Girlfriend
   - PremPubDate: 2020-07-17 18:30:00 UTC
   - FreePubDate: 2020-07-24 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0003|796249] 3 - Beach and Girlfriend
   - PremPubDate: 2020-07-24 18:30:00 UTC
   - FreePubDate: 2020-07-31 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0004|796250] 4 - Friend and Girlfriend
   - PremPubDate: 2020-07-31 18:30:00 UTC
   - FreePubDate: 2020-08-07 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0005|796251] 5 - Hot Springs and Girlfriend
   - PremPubDate: 2020-08-07 18:30:00 UTC
   - FreePubDate: 2020-08-14 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0006|796252] 6 - Girlfriend and Girlfriend
   - PremPubDate: 2020-08-14 18:30:00 UTC
   - FreePubDate: 2020-08-21 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0007|796253] 7 - Provisional Girlfriend and Girlfriend
   - PremPubDate: 2020-08-21 18:30:00 UTC
   - FreePubDate: 2020-08-28 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0008|796254] 8 - Christmas and Girlfriend
   - PremPubDate: 2020-08-28 18:30:00 UTC
   - FreePubDate: 2020-09-04 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0009|796255] 9 - Lies and Girlfriend
   - PremPubDate: 2020-09-04 18:30:00 UTC
   - FreePubDate: 2020-09-11 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0010|796256] 10 - Friend's Girlfriend
   - PremPubDate: 2020-09-11 18:30:00 UTC
   - FreePubDate: 2020-09-18 18:30:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0011|796257] 11 - Truth and Girlfriend
   - PremPubDate: 2020-09-18 18:30:00 UTC
   - FreePubDate: 2020-09-25 18:30:00 UTC (in 6d17h03m32s)
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU

[INFO] Selected Episodes: 0011

Requesting: [796257] Rent-a-Girlfriend - 11 - Truth and Girlfriend
[INFO] Cookies were updated! (etp_rt)

[INFO] Your region: US United States of America
[INFO] Your account: animety

[INFO] Selecting raw stream
[INFO] Full stream found! (1: adaptive_hls/jaJP)
[INFO] Full stream found! (2: multitrack_adaptive_hls_v2/jaJP)
[INFO] Full stream found! (3: vo_adaptive_hls/jaJP)
[INFO] Downloading video...
[INFO] Playlist URL:  (adaptive_hls/jaJP)
[WARN] Non duplicate url for pl.crunchyroll.com detected, please report to devel
oper!
[WARN] Non duplicate url for pl.crunchyroll.com detected, please report to devel
oper!
[WARN] Non duplicate url for pl.crunchyroll.com detected, please report to devel
oper!
[WARN] Non duplicate url for pl.crunchyroll.com detected, please report to devel
oper!
[WARN] Non duplicate url for pl.crunchyroll.com detected, please report to devel
oper!
[INFO] Servers available:
        pl.crunchyroll.com
[INFO] Available qualities:
         240p (548KiB/s)
         360p (1068KiB/s)
         480p (2043KiB/s)
         720p (4023KiB/s)
        1080p (7934KiB/s)
[INFO] Selected quality: 720p @ pl.crunchyroll.com
[INFO] Output filename: [CR] Rent-a-Girlfriend - 11 [720p]
[INFO] Total parts in stream: 733 (74*10)
[INFO] Saving stream to «videos\[CR] Rent-a-Girlfriend - 11 [720p].ts»...
[WARN] Part 8: NaN attempt to retrieve data
[ERROR] Part 8 download error:
        Cannot read property 'message' of undefined
[WARN] Part 9: NaN attempt to retrieve data
[ERROR] Part 9 download error:
        Cannot read property 'message' of undefined
[WARN] Part 7: NaN attempt to retrieve data
[ERROR] Part 7 download error:
        Cannot read property 'message' of undefined
[WARN] Part 10: NaN attempt to retrieve data
[ERROR] Part 10 download error:
        Cannot read property 'message' of undefined
[WARN] Part 4: NaN attempt to retrieve data
[ERROR] Part 4 download error:
        Cannot read property 'message' of undefined
[WARN] Part 6: NaN attempt to retrieve data
[ERROR] Part 6 download error:
        Cannot read property 'message' of undefined
[WARN] Part 5: NaN attempt to retrieve data
[ERROR] Part 5 download error:
        Cannot read property 'message' of undefined
[WARN] Part 3: NaN attempt to retrieve data
[ERROR] Part 3 download error:
        Cannot read property 'message' of undefined
[WARN] Part 2: NaN attempt to retrieve data
[ERROR] Part 2 download error:
        Cannot read property 'message' of undefined
[WARN] Part 1: NaN attempt to retrieve data
[ERROR] Part 1 download error:
        Cannot read property 'message' of undefined
[ERROR] 10 parts not downloaded
[ERROR] DL Stats: {"first":1,"total":733,"completed":0}

[INFO] Downloading subtitles...
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].01 eng English (U
S).ass
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].02 spa Spanish (L
atin American).ass
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].03 spa Spanish.as
s
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].04 fre French.ass

[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].05 por Portuguese
 (Brazilian).ass
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].06 ara Arabic.ass

[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].07 ita Italian.as
s
[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].08 ger German.ass

[INFO] Subtitle downloaded: [CR] Rent-a-Girlfriend - 11 [720p].09 rus Russian.as
s
[INFO] Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU

@ C:\Users\Administrator\Downloads\crunchyroll-downloader-nx-4.19.1-win64\crunch
yroll-downloader-nx-4.19.1-win64

>

**Comment by anidl** [comment]
fixed in 4.20.0

**Comment by giuband** [comment]
Hi @anidl , I'm still facing this issue with version 4.20.0. The error is still that
```
[WARN] Part 8: NaN attempt to retrieve data
[ERROR] Part 8 download error:
        Cannot read property 'message' of undefined
```
It's happening on about half of the files I'm trying

**Comment by bgette** [comment]
you using which version ?
.js or .exe ?

**Comment by giuband** [comment]
@bgette 🤦 Thanks, you're right. `npm i` solved it.
